version: '3.8'

services:
  # redis: # Name of container
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes: 
  #     - redis:/data
  #   networks:
  #     - reverse-proxy

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - reverse-proxy

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - reverse-proxy

  api:
    container_name: api
    build:
      context: ./pet_api
      dockerfile: Dockerfile.dev
      # Only will build development stage from our dockerfile
      target: development
    # env_file:
    #     - ./pet_api/.env
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./pet_api:/app
      - /app/node_modules
    ports:
      - 8080:8080
    depends_on:
    #   - redis
      - postgres
    networks:
      - reverse-proxy

  web:
    container_name: web
    depends_on: 
      - api
    build:
      context: ./pet_web
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./pet_web:/app
      - /app/node_modules
    networks:
      - reverse-proxy
    environment:
      - NODE_ENV=development

volumes:
  docker-nest-postgres:
  redis:
    driver: local

networks:
  reverse-proxy:
    name: reverse-proxy
