version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGODB_DATABASE: pet
    ports:
      - 27017:27017
    volumes:
      - docker-nest-mongo:/data/db
    networks:
      - pet-network

  api:
    container_name: api
    build:
      context: ./pet_api
      dockerfile: Dockerfile.dev
      # Only will build development stage from our dockerfile
      # target: development
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./pet_api:/app
      - /app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - pet-network

  web:
    container_name: web
    depends_on: 
      - api
    build:
      context: ./pet_web
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./pet_web:/app
      - /app/node_modules
    networks:
      - pet-network
    environment:
      - NODE_ENV=development
  
  # nginx:
  #   build: 
  #     context: nginx
  #   container_name: nginx
  #   restart: always
  #   tty: true
  #   ports: 
  #     - "8000:80"
  #   networks: 
  #     - pet-network
  #   depends_on:
  #      - api
  #      - web

volumes:
  docker-nest-mongo:

networks:
  pet-network:
    name: pet-network
